name: ci

on: [push, pull_request]

jobs:
  rust:
    name: deno_lint-${{ matrix.os }}
    if: |
      github.event_name == 'push' ||
      !startsWith(github.event.pull_request.head.label, 'denoland:')
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
        os: [windows-2019]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          submodules: true
          persist-credentials: false

      - name: Install rust
        uses: hecrj/setup-rust-action@v1.3.4
        with:
          rust-version: 1.53.0

      - name: Install clippy and rustfmt
        run: |
          rustup component add clippy
          rustup component add rustfmt

      - name: Install Deno
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.7.5

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: cache1-${{ runner.os }}-${{ github.sha }}
          restore-keys: cache1-${{ runner.os }}-

      - name: Environment
        run: |
          echo "GH_ACTIONS=1" >> ${GITHUB_ENV}
          echo "RUST_BACKTRACE=full" >> ${GITHUB_ENV}

      - name: Build and run
        run: cargo build --locked --release --all-targets && ./target/release/examples/dlint run ./maguro.ts
